apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb8
  namespace: es
spec:
  version: 8.11.0
  count: 1
  elasticsearchRef:
    name: es8
    namespace: es
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true