server:
  port: 8080
  host: 0.0.0.0

app:
    greeting: "Hello"

db:
  source: jdbc
  connection:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE"
    username: sa
    password:
    initializationFailTimeout: -1
    connectionTimeout: 2000
  health-check:
    type: "query"
    statementName: "health-check"
  statements:
    health-check: "SELECT 0"
    create-types: "CREATE TABLE PokeTypes (id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL)"
    create-pokemons: "CREATE TABLE Pokemons (id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL, id_type INTEGER NOT NULL REFERENCES PokeTypes(id))"
    select-all-types: "SELECT id, name FROM PokeTypes"
    select-all-pokemons: "SELECT id, name, id_type FROM Pokemons"
    select-pokemon-by-id: "SELECT id, name, id_type FROM Pokemons WHERE id = :id"
    select-pokemon-by-name: "SELECT id, name, id_type FROM Pokemons WHERE name = ?"
    insert-type: "INSERT INTO PokeTypes(id, name) VALUES(?, ?)"
    insert-pokemon: "INSERT INTO Pokemons(id, name, id_type) VALUES(?, ?, ?)"
    update-pokemon-by-id: "UPDATE Pokemons SET name = :name, id_type = :idType WHERE id = :id"
    delete-pokemon-by-id: "DELETE FROM Pokemons WHERE id = :id"
    delete-all-types: "DELETE FROM PokeTypes"
    delete-all-pokemons: "DELETE FROM Pokemons"

