apiVersion: v1
kind: Pod
metadata:
  annotations:
    co.elastic.logs/module: elasticsearch
    elasticsearch.k8s.elastic.co/config-hash: "552004593"
    update.k8s.elastic.co/timestamp: "2023-11-12T18:02:40.088152726Z"
  creationTimestamp: "2023-11-12T18:02:35Z"
  generateName: esm-es-metrics-
  labels:
    common.k8s.elastic.co/type: elasticsearch
    controller-revision-hash: esm-es-metrics-75b97bb479
    elasticsearch.k8s.elastic.co/cluster-name: esm
    elasticsearch.k8s.elastic.co/http-scheme: http
    elasticsearch.k8s.elastic.co/node-data: "true"
    elasticsearch.k8s.elastic.co/node-data_cold: "false"
    elasticsearch.k8s.elastic.co/node-data_content: "false"
    elasticsearch.k8s.elastic.co/node-data_frozen: "false"
    elasticsearch.k8s.elastic.co/node-data_hot: "false"
    elasticsearch.k8s.elastic.co/node-data_warm: "false"
    elasticsearch.k8s.elastic.co/node-ingest: "true"
    elasticsearch.k8s.elastic.co/node-master: "true"
    elasticsearch.k8s.elastic.co/node-ml: "false"
    elasticsearch.k8s.elastic.co/node-remote_cluster_client: "true"
    elasticsearch.k8s.elastic.co/node-transform: "false"
    elasticsearch.k8s.elastic.co/node-voting_only: "false"
    elasticsearch.k8s.elastic.co/statefulset-name: esm-es-metrics
    elasticsearch.k8s.elastic.co/version: 8.11.0
    statefulset.kubernetes.io/pod-name: esm-es-metrics-0
  name: esm-es-metrics-0
  namespace: esm
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: esm-es-metrics
    uid: 0d138000-8513-483f-a606-e3a19f11a1cf
  resourceVersion: "715779"
  uid: e61e0f97-1fad-4eb9-ad2e-889510ecb9d3
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              elasticsearch.k8s.elastic.co/cluster-name: esm
          topologyKey: kubernetes.io/hostname
        weight: 100
  automountServiceAccountToken: false
  containers:
  - env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: PROBE_PASSWORD_PATH
      value: /mnt/elastic-internal/pod-mounted-users/elastic-internal-probe
    - name: PROBE_USERNAME
      value: elastic-internal-probe
    - name: READINESS_PROBE_PROTOCOL
      value: http
    - name: HEADLESS_SERVICE_NAME
      value: esm-es-metrics
    - name: NSS_SDB_USE_CACHE
      value: "no"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - bash
          - -c
          - /mnt/elastic-internal/scripts/pre-stop-hook-script.sh
    name: elasticsearch
    ports:
    - containerPort: 9200
      name: http
      protocol: TCP
    - containerPort: 9300
      name: transport
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /_cluster/health
        port: 9200
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/elastic-internal/downward-api
      name: downward-api
      readOnly: true
    - mountPath: /usr/share/elasticsearch/bin
      name: elastic-internal-elasticsearch-bin-local
    - mountPath: /mnt/elastic-internal/elasticsearch-config
      name: elastic-internal-elasticsearch-config
      readOnly: true
    - mountPath: /usr/share/elasticsearch/config
      name: elastic-internal-elasticsearch-config-local
    - mountPath: /usr/share/elasticsearch/plugins
      name: elastic-internal-elasticsearch-plugins-local
    - mountPath: /usr/share/elasticsearch/config/http-certs
      name: elastic-internal-http-certificates
      readOnly: true
    - mountPath: /mnt/elastic-internal/pod-mounted-users
      name: elastic-internal-probe-user
      readOnly: true
    - mountPath: /usr/share/elasticsearch/config/transport-remote-certs/
      name: elastic-internal-remote-certificate-authorities
      readOnly: true
    - mountPath: /mnt/elastic-internal/scripts
      name: elastic-internal-scripts
      readOnly: true
    - mountPath: /usr/share/elasticsearch/config/transport-certs
      name: elastic-internal-transport-certificates
      readOnly: true
    - mountPath: /mnt/elastic-internal/unicast-hosts
      name: elastic-internal-unicast-hosts
      readOnly: true
    - mountPath: /mnt/elastic-internal/xpack-file-realm
      name: elastic-internal-xpack-file-realm
      readOnly: true
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-data
    - mountPath: /usr/share/elasticsearch/logs
      name: elasticsearch-logs
    - mountPath: /usr/share/elasticsearch/config/operator
      name: file-settings
      readOnly: true
    - mountPath: /tmp
      name: tmp-volume
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: esm-es-metrics-0
  nodeName: lima-rancher-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
  serviceAccount: default
  serviceAccountName: default
  subdomain: esm-es-metrics
  terminationGracePeriodSeconds: 180
  volumes:
  - name: elasticsearch-data
    persistentVolumeClaim:
      claimName: elasticsearch-data-esm-es-metrics-0
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
    name: downward-api
  - emptyDir: {}
    name: elastic-internal-elasticsearch-bin-local
  - name: elastic-internal-elasticsearch-config
    secret:
      defaultMode: 420
      optional: false
      secretName: esm-es-metrics-es-config
  - emptyDir: {}
    name: elastic-internal-elasticsearch-config-local
  - emptyDir: {}
    name: elastic-internal-elasticsearch-plugins-local
  - name: elastic-internal-http-certificates
    secret:
      defaultMode: 420
      optional: false
      secretName: esm-es-http-certs-internal
  - name: elastic-internal-probe-user
    secret:
      defaultMode: 420
      items:
      - key: elastic-internal-probe
        path: elastic-internal-probe
      - key: elastic-internal-pre-stop
        path: elastic-internal-pre-stop
      optional: false
      secretName: esm-es-internal-users
  - name: elastic-internal-remote-certificate-authorities
    secret:
      defaultMode: 420
      optional: false
      secretName: esm-es-remote-ca
  - configMap:
      defaultMode: 493
      name: esm-es-scripts
      optional: false
    name: elastic-internal-scripts
  - name: elastic-internal-transport-certificates
    secret:
      defaultMode: 420
      optional: false
      secretName: esm-es-metrics-es-transport-certs
  - configMap:
      defaultMode: 420
      name: esm-es-unicast-hosts
      optional: false
    name: elastic-internal-unicast-hosts
  - name: elastic-internal-xpack-file-realm
    secret:
      defaultMode: 420
      optional: false
      secretName: esm-es-xpack-file-realm
  - emptyDir: {}
    name: elasticsearch-logs
  - name: file-settings
    secret:
      defaultMode: 420
      optional: false
      secretName: esm-es-file-settings
  - emptyDir: {}
    name: tmp-volume
